name: LawBot Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev

      - name: Run chatbot
        env:
          HF_TOKEN: ${{secrets.HF_TOKEN}}   # put this in GitHub Secrets
        run: |
          pipenv run python connect_memory_with_llm.py <<EOF
          What is a crime?
          EOF
